common/models/ImgurAlbum.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "imgur_album".
 *
 * @property int $id
 * @property string $imgur_album_id
 *
 * @property ImgurImage[] $imgurImages
 */
class ImgurAlbum extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'imgur_album';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['imgur_album_id'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'imgur_album_id' => 'Imgur Album ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getImgurImages()
    {
        return $this->hasMany(ImgurImage::className(), ['album_id' => 'id']);
    }

    

}

frontend/models/ImgurAlbum.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "imgur_album".
 *
 * @property integer $id
 * @property string $imgur_album_id
 * @property string $title
 * @property string $description
 *
 * @property ImgurImage[] $imgurImages
 */
class ImgurAlbum extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'imgur_album';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['imgur_album_id', 'title', 'description'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'imgur_album_id' => 'Imgur Album ID',
            'title' => 'Title',
            'description' => 'Description',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getImgurImages()
    {
        return $this->hasMany(ImgurImage::className(), ['album_id' => 'id']);
    }


    //get my hndev2 album list
    public function getImgurAlbums()
    {
        $imgur = new ImgurApi;
        return $imgur->connect('get', 'account/hndev2/albums/');
    }

    public function saveToImgur($albumHash = '', $id = null){
        //die($albumHash);
        $params = [
            'id' => $id, //imageId, if any
            'title' => $this->title,
            'description' => $this->description
        ];


        $imgur = new ImgurApi;

        $response =  $imgur->connect(
              ($albumHash == '')?  'post' : 'put', //method 
              'album/'. $albumHash, //url
              $params
        );

        if($albumHash == '')
            return $response->data->id;
        else
            return $response->data;
        
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {

            if($this->isNewRecord){
                $this->imgur_album_id = $this->saveToImgur();
            }else{
                $this->saveToImgur($this->imgur_album_id);
            }
            

            return true;
        } else {
            return false;
        }
    }


}

frontend/controllers/ImgurAlbumController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\ImgurAlbum;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ImgurAlbumController implements the CRUD actions for ImgurAlbum model.
 */
class ImgurAlbumController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ImgurAlbum models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => ImgurAlbum::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionTest()
    {
        $model = new ImgurAlbum();
        $data = $model->getImgurAlbums();

        print_r( $data );
    }

    /**
     * Displays a single ImgurAlbum model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ImgurAlbum model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ImgurAlbum();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing ImgurAlbum model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing ImgurAlbum model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {

        $model = $this->findModel($id);

        $response = \app\models\ImgurApi::connect('delete', 'album/'.$model->imgur_album_id);
        
        $model->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the ImgurAlbum model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ImgurAlbum the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ImgurAlbum::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/ImgurImageController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\ImgurImage;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ImgurImageController implements the CRUD actions for ImgurImage model.
 */
class ImgurImageController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ImgurImage models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => ImgurImage::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ImgurImage model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ImgurImage model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ImgurImage();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionCreateByAlbum($id)
    {
        $album = $this->findAlbum($id);
        $model = new ImgurImage();
        $model->album_id = $id;
        $model->album_hash = $album->imgur_album_id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing ImgurImage model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing ImgurImage model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {

        $model = $this->findModel($id);

        $response = \app\models\ImgurApi::connect('delete', 'image/'.$model->imgur_image_id);
        
        $model->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the ImgurImage model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ImgurImage the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ImgurImage::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function findAlbum($id)
    {
        if (($model = \app\models\ImgurAlbum::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }




}

frontend/views/imgur-album/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ImgurAlbum */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="imgur-album-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'imgur_album_id')->hiddenInput(['maxlength' => true])->label(false) ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/imgur-album/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\ImgurAlbum */

$this->title = 'Create Imgur Album';
$this->params['breadcrumbs'][] = ['label' => 'Imgur Albums', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="imgur-album-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/imgur-album/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Imgur Albums';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="imgur-album-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Imgur Album', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'imgur_album_id',
            'title',
            'description',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

frontend/views/imgur-album/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ImgurAlbum */

$this->title = 'Update Imgur Album: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Imgur Albums', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="imgur-album-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/imgur-album/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\ImgurAlbum */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Imgur Albums', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="imgur-album-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Add Image', ['/imgur-image/create-by-album', 'id' => $_GET['id']], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'imgur_album_id',
            'title',
            'description',
        ],
    ]) ?>

</div>